const looks=[
{id:'1',title:'Soft Tailored Campus',vibe:'polished but easy',occasion:'campus',style:['minimal','soft'],hijab:['pashmina','square'],colors:{a:'#efe4d9',b:'#dac4b2',h:'#d8c6b6',t:'#6f1832',bt:'#f2ede7'},pieces:['oatmeal pashmina','maroon knit','wide-leg trousers']},
{id:'2',title:'Clean Modest Street',vibe:'relaxed Gen Z layers',occasion:'hangout',style:['street','minimal'],hijab:['pashmina','instant'],colors:{a:'#dedbd6',b:'#bdb6ae',h:'#2b2b2a',t:'#efe9df',bt:'#3c3a37'},pieces:['charcoal pashmina','oversized shirt','wide-leg pants']},
{id:'3',title:'Butter & Burgundy',vibe:'brand-coded statement',occasion:'event',style:['soft','minimal'],hijab:['pashmina','square'],colors:{a:'#fff0b3',b:'#f3d775',h:'#6f1832',t:'#f6e6a5',bt:'#7f2943'},pieces:['burgundy hijab','butter longline top','maxi skirt']},
{id:'4',title:'Gallery Girl Modest',vibe:'quietly editorial',occasion:'hangout',style:['mono','soft'],hijab:['square','pashmina'],colors:{a:'#e9e6e1',b:'#cbc5bc',h:'#b9aa99',t:'#ece7df',bt:'#6e635a'},pieces:['taupe scarf','boxy blazer','column skirt']},
{id:'5',title:'Modern Abaya Edit',vibe:'simple formal energy',occasion:'formal',style:['minimal','mono'],hijab:['pashmina','square','instant'],colors:{a:'#d8c9c6',b:'#a98288',h:'#efe4df',t:'#541527',bt:'#541527'},pieces:['soft beige hijab','clean-cut abaya','structured bag']},
{id:'6',title:'Airport Layering',vibe:'comfortable & put together',occasion:'travel',style:['street','minimal'],hijab:['pashmina','instant'],colors:{a:'#eee6db',b:'#d3c6b7',h:'#8f796a',t:'#f5f0e9',bt:'#393632'},pieces:['mocha pashmina','longline cardigan','wide-leg pants']}
];
let saved=JSON.parse(localStorage.getItem('ysSaved')||'[]');let wardrobe=JSON.parse(localStorage.getItem('ysWardrobe')||'null')||[{id:1,name:'Oatmeal Pashmina',cat:'Hijab',color:'#d8c6b6'},{id:2,name:'Maroon Knit Top',cat:'Top',color:'#6f1832'},{id:3,name:'Stone Wide-Leg Pants',cat:'Bottom',color:'#d8d0c5'},{id:4,name:'Taupe Long Blazer',cat:'Outer',color:'#aa9585'}];const state={occasion:'campus',style:'minimal',hijab:'pashmina'};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function card(l){const on=saved.includes(l.id);return `<article class='look'><div class='lookvisual' style='--a:${l.colors.a};--b:${l.colors.b}'><div class='minihead'></div><div class='minihijab' style='--h:${l.colors.h}'></div><div class='minitop' style='--t:${l.colors.t}'></div><div class='minibottom' style='--bt:${l.colors.bt}'></div></div><div class='lookbody'><button class='save ${on?'on':''}' data-save='${l.id}'>${on?'♥':'♡'}</button><h4>${l.title}</h4><p>${l.vibe}</p><div class='tags'>${l.pieces.map(x=>`<span>${x}</span>`).join('')}</div></div></article>`}
function renderFeatured(){$('#featured').innerHTML=looks.slice(0,3).map(card).join('')}function score(l){return(l.occasion===state.occasion?3:0)+(l.style.includes(state.style)?2:0)+(l.hijab.includes(state.hijab)?1:0)}function renderGenerated(){const r=[...looks].sort((a,b)=>score(b)-score(a)).slice(0,4);$('#generated').innerHTML=r.map(card).join('');$('#resultTitle').textContent=`${state.occasion[0].toUpperCase()+state.occasion.slice(1)} ${state.style[0].toUpperCase()+state.style.slice(1)} Edit`}function renderSaved(){const arr=saved.map(id=>looks.find(l=>l.id===id)).filter(Boolean);$('#savedGrid').innerHTML=arr.map(card).join('');$('#emptySaved').style.display=arr.length?'none':'block'}
function save(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem('ysSaved',JSON.stringify(saved));renderFeatured();renderGenerated();renderSaved()}document.addEventListener('click',e=>{const s=e.target.closest('[data-save]');if(s)save(s.dataset.save);const g=e.target.closest('[data-go]');if(g)show(g.dataset.go);const n=e.target.closest('[data-page]');if(n)show(n.dataset.page)});function show(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$('aside').classList.remove('open')}
$$('.chips button').forEach(b=>b.onclick=()=>{const group=b.parentElement.dataset.group;b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state[group]=b.dataset.value});$('#generate').onclick=renderGenerated;$('#surprise').onclick=()=>{show('planner');$('#generated').innerHTML=card(looks[Math.floor(Math.random()*looks.length)])};$('#menu').onclick=()=>$('aside').classList.toggle('open');
function renderWardrobe(){$('#wardrobeGrid').innerHTML=wardrobe.map(i=>`<article><div class='swatch' style='--c:${i.color}'></div><h4>${i.name}</h4><small>${i.cat}</small><button class='del' data-del='${i.id}'>remove</button></article>`).join('')}$('#wardrobeGrid').onclick=e=>{const b=e.target.closest('[data-del]');if(!b)return;wardrobe=wardrobe.filter(i=>String(i.id)!==b.dataset.del);localStorage.setItem('ysWardrobe',JSON.stringify(wardrobe));renderWardrobe()};$('#addItem').onclick=()=>$('#modal').classList.add('show');$('#close').onclick=()=>$('#modal').classList.remove('show');$('#form').onsubmit=e=>{e.preventDefault();wardrobe.push({id:Date.now(),name:$('#itemName').value,cat:$('#itemCat').value,color:$('#itemColor').value});localStorage.setItem('ysWardrobe',JSON.stringify(wardrobe));e.target.reset();$('#modal').classList.remove('show');renderWardrobe()};
const pals={dark:[['Stone','#CFC6BB'],['Mushroom','#A99888'],['Warm Ivory','#F2EBDD'],['Muted Mocha','#8B705F']],light:[['Cocoa','#7A5C4A'],['Burgundy','#6F1832'],['Deep Taupe','#77675E'],['Muted Olive','#7E8066']]};function lum(h){const c=h.slice(1),r=parseInt(c.slice(0,2),16),g=parseInt(c.slice(2,4),16),b=parseInt(c.slice(4),16);return(.299*r+.587*g+.114*b)/255}function renderMatches(){const h=$('#colorInput').value,arr=lum(h)<.5?pals.dark:pals.light;$('#matches').innerHTML=arr.map(([n,c])=>`<div class='match' style='--c:${c};--txt:${lum(c)<.5?'#fff':'#222'}'>${n}<br>${c}</div>`).join('')}$('#match').onclick=renderMatches;renderFeatured();renderGenerated();renderSaved();renderWardrobe();renderMatches();
